version: '2'

networks:
    NMPPP:

services:
    nginx:
        image: nginx:latest
        container_name: NMPPP_nginx
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - NMPPP

    mariaDB:
        image: mariadb:latest
        container_name: NMPPP_mariaDB
        volumes:
            - ./conf/mariadb:/var/lib/mysql:rw
        ports:
            - "3306:3306"
        depends_on:
            - nginx
        environment:
            - MYSQL_ROOT_PASSWORD=password
        networks:
            - NMPPP
    php:
        build: conf/php
        restart: always
        container_name: NMPPP_php
        volumes:
            - ./code:/code
        ports:
            - "9000:9000"
        networks:
            - NMPPP
    postgresql:
        image: postgres:latest
        container_name: NMPPP_postgresql
        ports:
          - "5432:5432"
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
        volumes:
          - ./conf/postgresql/:/var/lib/postgresql/data
        networks:
          - NMPPP

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: LEMP_phpMyAdmin
        ports:
            - "8188:80"
        environment:
            PMA_ARBITRARY: 1
        depends_on:
            - mariaDB
        networks:
            - NMPPP
